version: '3'

services:
  proxy:
    build: ./build
    container_name: proxy
    volumes:
     - ./conf.d:/etc/nginx/conf.d
    ports:
     - "80:80"
    restart: always

networks: 
  default:
    external:
      name: global
